#!/usr/bin/env bash
#SEND FILE TO SERVER
#client to server
if (( $# >= 3 )); then
    s=True
else
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit
fi
scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/ 
