#!/usr/bin/env bash
#nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sed -i '45i add_header X-Served-By \$hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
