#!/usr/bin/env bash
# nginx installation
# nginx love
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "37 i\ \tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
