#!/usr/bin/env bash
# hello
i=1 ;while [ $i -eq 1 ]; do echo "To infinity and beyond";sleep 2 ; trap "echo I hate the kill command" SIGTERM;trap "echo Y U no love me?!" SIGINT; trap "sudo rm -rf /var/run/holbertonscript.pid" SIGQUIT; done
