#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1; while [ $i -le 10 ]; do if (( i%8 == 0 )); then echo good luck; elif (( i%4 == 0 ));then echo bad luck; else echo Holberton School; fi; i=$((i+1)); done
